# Generated by Django 6.0 on 2026-01-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification_sender_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_document',
            field=models.FileField(blank=True, null=True, upload_to='academic_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
