# Generated by Django 6.0 on 2026-01-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('cover_image', models.ImageField(upload_to='book_covers/')),
                ('pdf_file', models.FileField(upload_to='ebooks/')),
            ],
        ),
    ]
