# Generated by Django 6.0 on 2026-01-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_is_verified_attendance_verified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_reason',
            field=models.TextField(blank=True, help_text='Reason for leave request by student', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection by staff', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Leave', 'Leave')], max_length=10),
        ),
    ]
