# Generated by Django 6.0 on 2026-02-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default='Semester 1', max_length=50),
        ),
    ]
